-- PostgreSQL 16 target schema for MSS sample stocking platform.
-- Use UUIDs generated by the application or pgcrypto gen_random_uuid().

create extension if not exists pgcrypto;

create type plan_status as enum (
  'PRODUCT_DRAFT', 'READY_TO_RELEASE', 'COLLECTING',
  'DOMAIN_REVIEW', 'GTM_CLOSURE', 'EXPORTED'
);
create type submission_status as enum ('NOT_STARTED', 'DRAFT', 'SUBMITTED', 'RETURNED');
create type org_type as enum ('REGION', 'OFFICE', 'COUNTRY');
create type import_status as enum ('UPLOADED', 'VALIDATING', 'MATCHING', 'COMPLETED', 'FAILED');
create type match_status as enum ('MATCHED', 'MAPPING_REQUIRED', 'UNMATCHED', 'DUPLICATE', 'INVALID');

create table app_user (
  id uuid primary key default gen_random_uuid(),
  employee_no varchar(64) not null unique,
  display_name varchar(128) not null,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version integer not null default 1
);

create table product_domain (
  id uuid primary key default gen_random_uuid(),
  code varchar(64) not null unique,
  name varchar(128) not null unique,
  description text,
  gtm_owner_id uuid not null references app_user(id),
  domain_owner_id uuid references app_user(id), -- legacy compatibility; MSS ownership is defined by mss_domain
  stocking_owner_id uuid not null references app_user(id),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version integer not null default 1
);

create table mss_domain (
  id uuid primary key default gen_random_uuid(),
  code varchar(64) not null unique,
  name varchar(256) not null,
  description text,
  mss_owner_id uuid references app_user(id),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version integer not null default 1
);

create table product (
  id uuid primary key default gen_random_uuid(),
  code varchar(64) not null unique,
  name varchar(256) not null,
  domain_id uuid not null references product_domain(id),
  mss_domain_id uuid references mss_domain(id),
  supply_time_text varchar(256),
  default_deadline_text varchar(128),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version integer not null default 1
);

create table product_sku (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references product(id),
  model varchar(256) not null,
  bom_code varchar(128),
  description text,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version integer not null default 1,
  unique(product_id, model)
);

create table org_node (
  id uuid primary key default gen_random_uuid(),
  code varchar(64) not null unique,
  name varchar(256) not null,
  node_type org_type not null,
  parent_id uuid references org_node(id),
  owner_id uuid references app_user(id),
  enabled boolean not null default true,
  valid_from timestamptz not null default now(),
  valid_to timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version integer not null default 1
);
create index idx_org_node_parent on org_node(parent_id);

create table master_data_alias (
  id uuid primary key default gen_random_uuid(),
  entity_type varchar(32) not null check (entity_type in ('SKU', 'REGION', 'OFFICE', 'COUNTRY')),
  entity_id uuid not null,
  source_system varchar(32) not null default 'TSMP',
  alias_value varchar(256) not null,
  normalized_value varchar(256) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version integer not null default 1,
  unique(source_system, entity_type, normalized_value)
);

create table collection_plan (
  id uuid primary key default gen_random_uuid(),
  plan_no varchar(64) not null unique,
  product_id uuid not null references product(id),
  domain_id uuid not null references product_domain(id),
  mss_domain_id uuid references mss_domain(id),
  sample_stage varchar(64) not null,
  status plan_status not null default 'READY_TO_RELEASE',
  deadline_at timestamptz not null,
  note text,
  released_by uuid references app_user(id),
  released_at timestamptz,
  created_by uuid not null references app_user(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version integer not null default 1
);
create index idx_collection_plan_product_status on collection_plan(product_id, status);
create index idx_collection_plan_product_stage_status on collection_plan(product_id, sample_stage, status);

create table collection_plan_scope (
  id uuid primary key default gen_random_uuid(),
  plan_id uuid not null references collection_plan(id),
  region_id uuid not null references org_node(id),
  region_name_snapshot varchar(256) not null,
  region_owner_snapshot varchar(128),
  office_country_snapshot jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version integer not null default 1,
  unique(plan_id, region_id)
);

create table demand_submission (
  id uuid primary key default gen_random_uuid(),
  plan_scope_id uuid not null unique references collection_plan_scope(id),
  status submission_status not null default 'NOT_STARTED',
  submitted_by uuid references app_user(id),
  submitted_at timestamptz,
  returned_by uuid references app_user(id),
  returned_at timestamptz,
  return_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version integer not null default 1
);

create table demand_item (
  id uuid primary key default gen_random_uuid(),
  submission_id uuid not null references demand_submission(id),
  product_sku_id uuid references product_sku(id),
  provisional_item_key varchar(256),
  office_id uuid not null references org_node(id),
  quantity integer not null default 0 check (quantity >= 0),
  demand_basis varchar(64),
  planned_use_date date,
  note varchar(500),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version integer not null default 1,
  check (product_sku_id is not null or provisional_item_key is not null),
  check (quantity = 0 or demand_basis is not null)
);
create unique index uq_demand_item_sku on demand_item(submission_id, office_id, product_sku_id) where product_sku_id is not null;
create unique index uq_demand_item_provisional on demand_item(submission_id, office_id, provisional_item_key) where provisional_item_key is not null;

create table domain_feedback (
  id uuid primary key default gen_random_uuid(),
  plan_id uuid not null unique references collection_plan(id),
  note text not null,
  total_quantity integer not null check (total_quantity >= 0),
  summary_snapshot jsonb not null,
  confirmed_by uuid not null references app_user(id),
  confirmed_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version integer not null default 1
);

create table production_export (
  id uuid primary key default gen_random_uuid(),
  plan_id uuid not null references collection_plan(id),
  plan_version integer not null,
  file_name varchar(256) not null,
  storage_key varchar(512),
  row_count integer not null,
  data_snapshot jsonb not null,
  exported_by uuid not null references app_user(id),
  exported_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version integer not null default 1
);

create table tsmp_import_job (
  id uuid primary key default gen_random_uuid(),
  file_name varchar(256) not null,
  file_hash varchar(128),
  storage_key varchar(512),
  status import_status not null default 'UPLOADED',
  total_rows integer not null default 0,
  matched_rows integer not null default 0,
  mapping_required_rows integer not null default 0,
  unmatched_rows integer not null default 0,
  duplicate_rows integer not null default 0,
  error_message text,
  imported_by uuid not null references app_user(id),
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version integer not null default 1,
  unique(file_hash)
);

create table tsmp_shipment_raw (
  id uuid primary key default gen_random_uuid(),
  import_job_id uuid not null references tsmp_import_job(id),
  source_row_no integer not null,
  external_key varchar(256),
  application_no varchar(128),
  raw_sku varchar(256),
  raw_bom varchar(128),
  raw_region varchar(256),
  raw_office varchar(256),
  raw_country varchar(256),
  shipped_quantity integer,
  shipped_at timestamptz,
  row_fingerprint varchar(128) not null,
  raw_payload jsonb not null,
  match_status match_status not null,
  match_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version integer not null default 1
);
create index idx_tsmp_shipment_fingerprint on tsmp_shipment_raw(row_fingerprint);

create table execution_fact (
  id uuid primary key default gen_random_uuid(),
  source_type varchar(32) not null check (source_type in ('CONFIRMED_DEMAND', 'PRODUCTION', 'APPLICATION', 'SHIPMENT', 'INVENTORY')),
  source_id uuid,
  product_id uuid not null references product(id),
  product_sku_id uuid references product_sku(id),
  region_id uuid references org_node(id),
  office_id uuid references org_node(id),
  country_id uuid references org_node(id),
  quantity integer not null,
  occurred_at timestamptz not null,
  dimension_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version integer not null default 1
);
create index idx_execution_fact_dimensions on execution_fact(product_id, product_sku_id, region_id, office_id, country_id, source_type);

create table inventory_balance (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references product(id),
  product_sku_id uuid not null references product_sku(id),
  warehouse varchar(256) not null,
  system_quantity integer not null default 0,
  actual_quantity integer not null default 0,
  locked_quantity integer not null default 0,
  available_quantity integer not null default 0,
  reason varchar(512),
  checked_by uuid references app_user(id),
  checked_at timestamptz,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version integer not null default 1,
  unique(product_sku_id, warehouse)
);
create index idx_inventory_balance_product on inventory_balance(product_id, product_sku_id, enabled);

create table audit_log (
  id uuid primary key default gen_random_uuid(),
  actor_id uuid references app_user(id),
  action varchar(128) not null,
  entity_type varchar(64) not null,
  entity_id uuid,
  before_data jsonb,
  after_data jsonb,
  request_id varchar(128),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version integer not null default 1
);
create index idx_audit_entity on audit_log(entity_type, entity_id, created_at desc);
