export enum ROLES {
  GTM = 'GTM',
  MSS_DOMAIN_OWNER = 'MSS_DOMAIN_OWNER',
  REGIONAL_OWNER = 'REGIONAL_OWNER',
  STOCKING_OWNER = 'STOCKING_OWNER',
}

export const ROLE_LABELS: Record<ROLES, string> = {
  [ROLES.GTM]: 'GTM',
  [ROLES.MSS_DOMAIN_OWNER]: 'MSS领域接口人',
  [ROLES.REGIONAL_OWNER]: '区域/代表处接口人',
  [ROLES.STOCKING_OWNER]: '备货接口人',
};

export enum PLAN_STATUS {
  PRODUCT_DRAFT = 'PRODUCT_DRAFT',
  READY_TO_RELEASE = 'READY_TO_RELEASE',
  COLLECTING = 'COLLECTING',
  DOMAIN_REVIEW = 'DOMAIN_REVIEW',
  GTM_CLOSURE = 'GTM_CLOSURE',
  EXPORTED = 'EXPORTED',
}

export const PLAN_STATUS_LABELS: Record<PLAN_STATUS, string> = {
  [PLAN_STATUS.PRODUCT_DRAFT]: '产品建档',
  [PLAN_STATUS.READY_TO_RELEASE]: '待下发',
  [PLAN_STATUS.COLLECTING]: '收集中',
  [PLAN_STATUS.DOMAIN_REVIEW]: '待领域反馈',
  [PLAN_STATUS.GTM_CLOSURE]: '待GTM收口',
  [PLAN_STATUS.EXPORTED]: '已导出',
};
